# To open ports visit Settings, Add ons, Frigate, Configuration

mqtt:
  enabled: True
  host: 192.168.52.210 # Localhost (worked with 192.168.52.210)
  port: 1883
  user: MQTT_HA
  password: N4yybdYtfCVc8e
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

# Enable the Coral.ai Edge TPU acceleration
detectors:
  coral:
    type: edgetpu
    device: usb
    model:
#     path: "/custom_model.tflite" # this is only for using your own model.  

ffmpeg:
  hwaccel_args: preset-vaapi

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: True
  # Optional: Width of the output resolution (default: shown below)
  width: 2560
  # Optional: Height of the output resolution (default: shown below)
  height: 1920
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always

go2rtc:
  streams:
    Driveway_5MP_Main:
      - "ffmpeg:http://192.168.52.77/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=trustno1"
    Driveway_5MP_Sub: 
     - "ffmpeg:http://192.168.52.77/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=trustno1"
    Backyard_5MP_Main:
      - "ffmpeg:http://192.168.52.78/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=trustno1"

# Global detect settings (unless overridden per camera)
detect:
  width: 1920
  height: 1080
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - cat
    - dog
    - bicycle
    - motorcycle

# Global record settings (unless overridden per camera)
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: active_objects
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 2
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 2
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
     #- person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 14
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: active_objects
      # Optional: Per object retention days
      objects:
        person: 14

# Global snaphot settings (unless overridden per camera)
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: True
  # Optional: height to resize the snapshot to (default: original size)
  # height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30
    # Optional: Per object retention days
    objects:
      person: 30


#################
# CAMERA CONFIG #
#################

cameras:
# Default RTSP Camera Configs

# Front Steps FHD # ########################################################################################################################################

  Front_Steps_FHD:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:trustno1@192.168.52.92/H264?ch=1&subtype=0
          roles:
            - detect
            - record
    birdseye:
      mode: objects
    motion:
      mask:
        - 1920,0,1920,44,1269,107,1165,0 # Timestamp
        - 137,189,62,471,23,615,0,723,0,0,210,0 # Road & sidewalk
    record:
      events:
        required_zones:
          - front_steps
    snapshots:
      required_zones:
          - front_steps
    zones:
      front_steps:
        coordinates: 1920,0,213,0,200,39,57,486,0,1080,1920,1080
        objects:
          - car
          - person
          - cat
          - dog
        filters:
          cat:
            min_area: 25000
            max_area: 150000
          dog:
            min_area: 25000
            max_area: 200000

# Front Yard FHD # ########################################################################################################################################

  Front_Yard_FHD:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:trustno1@192.168.52.89/H264?ch=1&subtype=0
          roles:
            - detect
            - record
    birdseye:
      mode: objects
    motion:
      mask:
      - 0,0,1385,0,1920,0,1920,1002,1399,661,1437,525,1156,356,860,357,404,388,867,1080,0,1080 # Road, sidewalk, hedge and front porch windows
    record:
      events:
        required_zones:
          - front_yard
    snapshots:
      required_zones:
          - front_yard
    zones:
      front_yard:
        coordinates: 1920,1010,1920,1080,0,1080,0,413,825,336,1499,317,1402,676
        objects:
          - car
          - person
          - cat
          - dog

# Front Porch FHD # ########################################################################################################################################

  Front_Porch_FHD:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:trustno1@192.168.52.100:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    birdseye:
      mode: objects
    record:
      events:
        required_zones:
          - front_porch
    snapshots:
      required_zones:
          - front_porch
    zones:
      front_porch:
        coordinates: 1367,0,1372,94,1920,93,1920,1080,0,1080,0,0
        objects:
          - car
          - person
          - cat
          - dog

# Carport QHD # ########################################################################################################################################

  Carport_180_QHD:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.52.88:554/user=admin&password=trustno1&channel=1&stream=0.sdp?
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1440
    birdseye:
      mode: objects
    motion:
      mask:
        - 2560,166,2560,476,2184,236,1834,88,1820,277,1431,165,1010,170,828,189,729,217,681,71,579,107,457,147,353,204,255,272,166,345,0,514,0,0,2560,0 # Road & sidewalk
    record:
      events:
        required_zones:
          - driveway
          - carport
    snapshots:
      required_zones:
          - driveway
          - carport
    zones:
      driveway:
        coordinates: 1015,182,1420,177,1713,397,1236,378,793,395
        objects:
          - car
          - person
          - cat
          - dog
      carport:
        coordinates: 0,1440,0,493,81,370,206,249,389,141,554,83,706,41,719,476,1233,461,1512,461,1791,480,1826,87,2281,211,2560,486,2560,1440 # The covered driveway area under the carport
        objects:
#         - car # don't bother telling me about cars under the carport
          - person
          - cat
          - dog
        filters:
          person:
            max_area: 1000000 # bug on lens detected as huge person
            mask: 1701,158,1720,440,1420,438,1425,154 # tarp over wood pile is not a person

# East Side Yard ##################################################################################################################################################

  East_Side_Yard_180_3MP:
    enabled: True
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:trustno1@192.168.52.98:554/channel=1&stream=0.sdp?real_stream
          roles:
            - detect
            - record
    detect:
      width: 2304
      height: 1296
    birdseye:
      mode: objects
    motion:
      mask:
        - 1956,513,1189,399,374,471,0,572,0,0,2304,0,2304,655
    record:
      events:
        required_zones:
          - east_side_yard
    snapshots:
      required_zones:
          - east_side_yard
    zones:
      east_side_yard:
        coordinates: 366,465,1185,404,1701,446,1972,521,2234,600,2304,1296,0,1272,0,592
        objects:
          - person
          - cat
          - dog

# Driveway 5MP # ########################################################################################################################################

# Reolink Camera Config (restreamed from http via go2rtc above)
  Driveway_5MP:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway_5MP_Main?video=copy&audio=aac # Running record off restream with audio
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1920
    birdseye:
      mode: continuous
    motion:
      mask:
        - 2560,0,408,0,378,287,486,302,588,370,905,432,1281,516,1760,654,2357,863,2118,1285,1891,1920,2560,1920 # Don't watch for motion on the road, sidewalk & bushes
    record:
      events:
        required_zones:
          - front_lawn
          - driveway
          - carport
    snapshots:
      required_zones:
          - front_lawn
          - driveway
          - carport
    zones:
      driveway:
        coordinates: 2560,1920,0,1920,0,960,649,813,993,768,1626,684,2560,1034 # The uncovered driveway area
        objects:
          - car
          - person
          - cat
          - dog
        filters:
          person:
            max_area: 615000 # tarp over wood pile is too large to be a person
      front_porch:
        coordinates: 490,312,373,288,414,0,0,0,0,973,626,830,615,503 # The front porch and steps
        objects:
#         - car # don't bother looking for cars on the porch. 
          - person
          - cat
          - dog
      front_lawn:
        coordinates: 984,748,612,709,608,510,514,345,729,416,1238,535,1668,667 # The front lawn
        objects:
#         - car # don't bother looking for cars on the lawn.  
          - person
          - cat
          - dog

# Backyard_5MP #################################################################################################################################

  Backyard_5MP:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Backyard_5MP_Main?video=copy&audio=aac # Running off scrypted rebroadcast
          roles:
            - record
            - detect
    detect:
      width: 2560
      height: 1920
    birdseye:
      mode: objects
    record:
      events:
        required_zones:
          - backyard
    snapshots:
      required_zones:
          - backyard
    zones:
      backyard:
        coordinates: 2560,1920,0,1920,0,727,630,532,1081,466,2560,811 # The uncovered driveway area
        objects:
          - bicycle
          - person
          - cat
          - dog
        filters:
          cat:
           mask: 104,1663,350,1654,326,1245,94,1249 # garden owl decoy is not a cat
#         motorcycle:
#           mask: 1573,1488,1574,1729,1753,1807,1936,1696,2053,1543,2054,1367,1895,1282,1742,1287 # winter tires are not a motorcycle
          person:
            mask: 2484,1230,2352,1677,2139,1595,2279,1174 # propane tanks are not a person
